### ISSUE TITLE
Install works - but salt throws openstack lib exceptions

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/devstack-formula#28]
Noise or worse.  Not seen on CentOS 7.
```
[ERROR   ] Failed to import module glance, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/glance.py", line 73, in <module>
    from keystoneclient.v2_0 import client as kstone
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module keystone, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/keystone.py", line 64, in <module>
    from keystoneclient.v2_0 import client
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module neutron, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/neutron.py", line 74, in <module>
    import salt.utils.openstack.neutron as suoneu
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/neutron.py", line 25, in <module>
    import keystoneauth1.loading
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/__init__.py", line 13, in <module>
    from keystoneauth1.loading import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/adapter.py", line 13, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module glance, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/glance.py", line 73, in <module>
    from keystoneclient.v2_0 import client as kstone
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module keystone, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/keystone.py", line 64, in <module>
    from keystoneclient.v2_0 import client
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module neutron, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/neutron.py", line 74, in <module>
    import salt.utils.openstack.neutron as suoneu
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/neutron.py", line 25, in <module>
    import keystoneauth1.loading
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/__init__.py", line 13, in <module>
    from keystoneauth1.loading import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/adapter.py", line 13, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module glance, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/glance.py", line 73, in <module>
    from keystoneclient.v2_0 import client as kstone
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module keystone, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/keystone.py", line 64, in <module>
    from keystoneclient.v2_0 import client
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module neutron, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/neutron.py", line 74, in <module>
    import salt.utils.openstack.neutron as suoneu
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/neutron.py", line 25, in <module>
    import keystoneauth1.loading
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/__init__.py", line 13, in <module>
    from keystoneauth1.loading import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/adapter.py", line 13, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module glance, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/glance.py", line 73, in <module>
    from keystoneclient.v2_0 import client as kstone
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module keystone, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/keystone.py", line 64, in <module>
    from keystoneclient.v2_0 import client
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module neutron, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/neutron.py", line 74, in <module>
    import salt.utils.openstack.neutron as suoneu
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/neutron.py", line 25, in <module>
    import keystoneauth1.loading
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/__init__.py", line 13, in <module>
    from keystoneauth1.loading import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/adapter.py", line 13, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module glance, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/glance.py", line 73, in <module>
    from keystoneclient.v2_0 import client as kstone
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module keystone, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/keystone.py", line 64, in <module>
    from keystoneclient.v2_0 import client
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 25, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
[ERROR   ] Failed to import module neutron, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib/python2.7/dist-packages/salt/modules/neutron.py", line 74, in <module>
    import salt.utils.openstack.neutron as suoneu
  File "/usr/lib/python2.7/dist-packages/salt/utils/openstack/neutron.py", line 25, in <module>
    import keystoneauth1.loading
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/__init__.py", line 13, in <module>
    from keystoneauth1.loading import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/loading/adapter.py", line 13, in <module>
    from keystoneauth1 import adapter
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 16, in <module>
    from keystoneauth1 import session
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py", line 1292, in <module>
    REQUESTS_VERSION = tuple(int(v) for v in requests.__version__.split('.'))
AttributeError: 'module' object has no attribute 'split'
```

**Comment by noelmcloughlin** [comment]
Seems this can be ignored.
